### PR TITLE
return right away so a success looks like "1" instead of "1 0"

### PR DESCRIPTION
**Pull request by hotpocket**
I use PROMPT_COMMAND for a custom prompt of my own and this code clobbers my prompt.  In my efforts to isolate the parts I want I ran across this issue which smells like a bug.

### CODE REVIEW

**Comment by magicmonty** [comment]
@ogr3 Thanks for checking this. 
I prefer also an if then else over the proposed solution.
@hotpocket could you please change this, then I will merge this in.

**Comment by hotpocket** [comment]
I too like the if else struct as it is cleaner. I am wondering now though if I should restructure things a bit so it returns 0 or 1 so we don't need to capture the stdout to test the success of this function.

On my Chromebook now but I can push this out tomorrow as an if/else if the above idea doesn't sound appealing.

Thanks.

**Comment by ogr3** [comment]
It's a bit of a mixed bag in bash whether return values are used and the result in stdout is used.

So since the usage of this function expects it to use stdout, just staying with an if-then-else leaving the rest intact is the cleaner patch for now I think.

So I'd suggest to do that for now.

**Comment by hotpocket** [comment]
So I can't help but wonder if it's better to have it in the former state because it is guaranteed to be at least 0, whereas here we may get empty string potentially...  

If this all sounds like rubbish then there is the already committed patch on my branch.

cheers

**Comment by magicmonty** [comment]
@hotpocket @ogr3  Thanks a lot

**Pull request merged**
