### PR TITLE
Fix bug in gitstatus.sh. If a file is modified in the index and at the same time in the work tree

### PR DESCRIPTION
**Pull request by tuxinaut**
**_Starting point:**_

✔  22:54 ~/workspace/aws-cli [ develop {origin/develop} | ✚ 1 ] $ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

```
   modified:   tox.ini
```

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
   modified:   tox.ini
```

**_Current output:**_

✔  22:54 ~/workspace/aws-cli [ develop {origin/develop} | ✚ 1 ] $ git status

**_Expected output:**_

✔  22:54 ~/workspace/aws-cli [ develop {origin/develop} | ● 1 ✚ 1 ] $ git status

### CODE REVIEW

**Comment by ogr3** [comment]
You have the same behaviour if teh file has been added to the index and then modified.

(Sorry for the swedish output, but you get the idea)

```sh
git status
På grenen master
Din gren är à jour med "origin/master".

Ändringar att checka in:
  (använd "git reset HEAD <fil>..." för att ta bort från kö)

	ny fil:        a

Ändringar ej i incheckningskön:
  (använd "git add <fil>..." för att uppdatera vad som skall checkas in)
  (använd "git checkout -- <fil>..." för att förkasta ändringar i arbetskatalogen)

	ändrad:        a
```

```sh
git status --porcelain
AM a
```

I have a nagging feeling about this being a bit complex - we had quite a long discussion when gitstatus.sh was created about a year ago. But it definately differs in behaviour from the old `gitstatus_pre-1.7.10.sh`, which you can use for reference.

**Comment by ogr3** [comment]
You should look at all possible outcomes of git status from the documentation and decide wheter you want a file to be counted twice or not.

As of now gitstatus will not count any file more than once.

```sh
X          Y     Meaning                          gitstatus.sh
--------------------------------------------------------------
          [MD]   not updated                      num_changed
M        [ MD]   updated in index                 num_changed
A        [ MD]   added to index                   num_staged if Y blank, otherwise num_changed
D         [ M]   deleted from index               num_staged if Y blank, otherwise num_changed
R        [ MD]   renamed in index                 num_staged if Y blank, otherwise num_changed
C        [ MD]   copied in index                  num_staged if Y blank, otherwise num_changed
[MARC]           index and work tree matches
[ MARC]     M    work tree changed since index    num_changed
[ MARC]     D    deleted in work tree             num_changed
-------------------------------------------------------------
D           D    unmerged, both deleted           num_changed
A           U    unmerged, added by us            num_staged
U           D    unmerged, deleted by them        num_changed
U           A    unmerged, added by them          num_conflicts
D           U    unmerged, deleted by us          num_staged
A           A    unmerged, both added             num_staged
U           U    unmerged, both modified          num_conflicts
---------------------------------------------------------------
?           ?    untracked                        num_untracked
!           !    ignored
---------------------------------------------------------------
```

**Comment by tuxinaut** [comment]
Thx for all the information. I didn't know that there was a bigger discussion in the past. For me it was a clear bug :smile: 

But there are any thoughts to change this behavior?

**Comment by ogr3** [comment]
There haven't been until you filed this :)

I'll think about the different cases and desired behaviour.

**Comment by tuxinaut** [comment]
That would be great. :blush: thx

**Comment by ogr3** [comment]
#267 has been merged - I haven't had the chance to analyze how it compares to the table in this PR, but your original concern is taken care of at least. @tuxinaut

**Comment by tuxinaut** [comment]
I'm going to try that out :). Thx again for working on it.

**Comment by ogr3** [comment]
New approach in #269.

**Comment by ogr3** [comment]
Have you had a chance to try the latest version @tuxinaut? If so, you might close this if it works.

**Comment by tuxinaut** [comment]
Outdated

**Pull request closed without merging**
