### PR TITLE
Add GIT_PROMPT_SYMBOLS_PRETAG and GIT_PROMPT_DETACHED_HEAD

### PR DESCRIPTION
**Pull request by baincd**
GIT_PROMPT_SYMBOLS_PRETAG - prefix symbol for detached head state pointing to a tag (similar to PREHASH)
GIT_PROMPT_DETACHED_HEAD - variable tag/hash when in a detached state.

Note: I only modified gitstatus.sh.  Does gitstatus.py need to be kept in sync?

I'll happily accept any feedback on these changes!

### CODE REVIEW

**Comment by guenhter** [comment]
@baincd  could you rebase onto the latest main?

**Comment by baincd** [comment]
@guenhter Sorry, I'm not using bash-git-prompt now.  Hopefully, someone else can take these changes and apply them to main.  

All the best,
-Chris

**Comment by guenhter** [comment]
Allright. I'll leave it open for a couple of month and when noone takes over, I'll close it then.

**Comment by guenhter** [comment]
Closed via https://github.com/magicmonty/bash-git-prompt/pull/522

**Pull request closed without merging**
