### PR TITLE
Make sure aliases for cp and rm are lower priority than the original …

### PR DESCRIPTION
**Pull request by ogr3**
…command

People that have made aliases for rm and/or cp with the `-i` flag are experiencing that the prompt hangs now.

See http://stackoverflow.com/a/15951879/236365

Thanks to @gcbartlett 

Unsure whether we should have -f on either cp or rm though. It depends on whether the naming of the generated statusfile is unique I guess @DrVanScott

### CODE REVIEW

**Comment by DrVanScott** [comment]
i would say don't use "-f" in either case.

Maybe more important: Shouldn't we use

    command rm

instead of

    \rm

Maybe there are some users out there overriding "rm" with a function. Same applies to cp.

To be honest, i think alias-overriding standard commands is bad behaviour. Look for all those commands used in this project, we actually also must replace

    command git
    command echo
    command eval
    command cd
    command pwd
    ...

No, i am just kidding. Users just shouldn't override standard commands in an incompatible way. So @haraldkoch  maybe should better use "rm -I" (capital i) instead of "rm -i"?

Anyway, If you decide to accept this PR i would opt for "command rm" instead of "\rm"...

**Comment by haraldkoch** [comment]
aliases (and functions) are local to the current shell, and I only override commands in interactive shells. This project is unique in that it runs as part of the interactive shell.

I've been burned one too many times by a careless `rm` in the wrong place...

**Comment by ogr3** [comment]
I agree with you @DrVanScott in that we shouldn't take into account every possible command that can be overridden. I'm also thinking that the one that is most possible is someone using `rm -i` as alias for rm, so the special case when we do something in the background in the interactive shell is a candidate for 'unaliasing'. Using the reserved word command looks less hacky than using a backslash, so I'm all for that. Removed the `-f` on rm as well.

**Comment by magicmonty** [comment]
Awesome,thanks

**Pull request merged**
