### PR TITLE
Unified variable format and made it more robust agains set -u

### PR DESCRIPTION
**Pull request by magicmonty**
Unified the variable format to a common standard (`"${VARNAME}"`).

@ogr3 Could you be so nice and check against your system? Especially as I don't have access to OSX anymore.

*Edit*: Reverted back to `+x`

### CODE REVIEW

**Comment by ogr3** [comment]
Testtes teh latest version on Ubuntu. Looks better, but gitstatus bombs:

./gitstatus.sh 
`fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths`

**Comment by magicmonty** [comment]
@ogr3 found it and fixed it

**Comment by ogr3** [comment]
Did a quick test on macOS and got a different error:

```bash
./gitstatus.sh
Cleanup

.
upstream/Cleanup
0
0
0
0
2
0
-bash: mapfile: command not found
```

**Comment by ogr3** [comment]
mapfile does not exist on macOS. It will probably break other older versions of bash as well:

https://stackoverflow.com/questions/41475261/need-alternative-to-readarray-mapfile-for-script-on-older-version-of-bash

**Comment by ogr3** [comment]
Also i forgot to mention that the gitinfo does not show at all on MacOS :( The path showed ok, but not the brackets with git info.

Didn't have time to test more than that. @magicmonty

**Comment by ogr3** [comment]
Quick test in Ubuntu on my Theme shows upstream info unconditionally - which it should not.

`.../github/bash-git-prompt] [Cleanup {upstream/Cleanup}|✚ 1]`

**Comment by magicmonty** [comment]
@ogr3 Fixed the unconditionally shown upstream info

**Comment by ogr3** [comment]
Nice, I'm running from the Cleanup branch now on my daily driver Ubuntu machine for some battle testing.

Will do some more testing on macOS later.

**Comment by magicmonty** [comment]
@ogr3 Cool, thank you for your help

**Comment by ogr3** [comment]
Tested this latest version now on macOS - still no git section visible at all in the prompt. No error messages. 

gitstatus seem to deliver the correct values, but the git data in the prompt is a no show. 

Tested with my standard theme as well as the default theme.

**Comment by ogr3** [comment]
There is something not working right with the creation of the array from gitstatus on macOS.

I also had to change this line:

`if [[ -z "${__GIT_STATUS_CMD:+x}" ]] ; then ´

adding the colon in order for it to execute the gitstatus command.

Then I got the git status part of the prompt, but no numbers, just the branch name and the symbols.

No more time to test it today

**Comment by ogr3** [comment]
In the earlier version there was a space between the path and the git info, it is missing in the latest version on this branch:
`✔ ~/Dokument/github/bash-git-prompt[Cleanup ↑·7|✚ ⚑ ]`

**Comment by magicmonty** [comment]
@ogr3  So if there are no further complaints, I will merge this tonight. ;)

**Pull request merged**
