### PR TITLE
Add new theme BlackOrWhite

### PR DESCRIPTION
**Pull request by norbertszivos**
I'm using a modified bash prompt to show git branch in the prompt, but special git informations were missing. When I found your awesome project I decided that I would like to use it. So I created a new theme with that prompt what I'm using and I thought if I already worked on it then I would like to share with you.

black_prompt
white_prompt
borwthemewithnerdfontsblack
borwthemewithnerdfontswhite
bgpbowbwdl
bgpbowp

### CODE REVIEW

**Comment by ackzell** [comment]
Stumbled upon this. Just wanted to thank you for sharing it @norbertszivos !
It looks gorgeous 😁

**Comment by WizBangCrash** [comment]
I came across your theme last week and I'm hooked on it. Thanks @norbertszivos

**Comment by vitaly-zdanevich** [comment]
No special color for root user?

**Comment by norbertszivos** [comment]
> No special color for root user?

No, there is not any special color for root. It changes the dot to exclamation mark if you change user to root.
That is why I called it black or white because it is “monochrome”.

**Comment by vitaly-zdanevich** [comment]
This is not related to this beautiful theme, just a question: maybe do you know how to highlight the line with that bash-prompt? I want to improve visibility when I scroll my terminal window.

**Comment by norbertszivos** [comment]
Hey @vitaly-zdanevich!
Good question 🤔 
I guess this is not what you are looking for, but maybe it can be a good staring point: [highlight-current-bash-prompt-line](https://unix.stackexchange.com/questions/250340/highlight-current-bash-prompt-line)

**Pull request merged**
