### PR TITLE
Solves issue #252: error message in prompt with old bash version

### PR DESCRIPTION
**Pull request by tiagocoutinho**
I think this will solve the problem for old bash versions

### CODE REVIEW

**Comment by magicmonty** [comment]
Thanks alot

**Comment by matt-smiley** [comment]
Unfortunately this patch breaks under all the recent bash versions I've tested.  Specifically, the call to bash's "test" command in "__chk_gitvar_status" at line 487 does the wrong thing, because "test" does not evaluate a quoted string like "eval" does; instead, according to its manpage, it treats a string the same as -n string.

```
$ man test
...
       An omitted EXPRESSION defaults to false.  Otherwise, EXPRESSION is true or false and sets exit status.  It is one of:
...
       -n STRING
              the length of STRING is nonzero

       STRING equivalent to -n STRING
```

Consequently, here's what the prompt of a clean branch looks like:

```
msmiley@ariadne:~/src/git/public/bash-git-prompt [master|●0✖ 0✚ 0…0⚑ 1✔] $ 
```

In a nutshell, the following unexpectedly returns true (0), which is why gitprompt.sh is now showing the fields that have zero counters:

```
$ test '0 -ne 0' ; echo $?
0
```

whereas the unquoted version returns false (1), as you'd expect:

```
$ test 0 -ne 0 ; echo $?
1
```

Attached is a toy script showing the behavior of bash's "test" builtin command.

[exercise_bash_test_construct.sh.txt](https://github.com/magicmonty/bash-git-prompt/files/296048/exercise_bash_test_construct.sh.txt)

I get the same results when running it under bash 4.2.46 (on CentOS 7.2) and bash 4.3.11 (on Ubuntu 14.04).  Here's sample output:

```
msmiley@ariadne:~$ ./exercise_bash_test_construct.sh 
+ bash --version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
+ echo '"test" does evaluate an unquoted expression'
"test" does evaluate an unquoted expression
+ test 0 -eq 0
+ echo true
true
+ test 1 -eq 0
+ echo false
false
+ echo '"test" does not evaluate a quoted string'
"test" does not evaluate a quoted string
+ test '0 -eq 0'
+ echo true
true
+ test '1 -eq 0'
+ echo true
true
+ set +x
```

**Comment by ogr3** [comment]
The quote seems to be misplaced in the pr, it should not enclose both parameters, just $GIT_$1

Does that work?

**Comment by matt-smiley** [comment]
Oh yeah, you mean like this, right?
```
diff --git a/gitprompt.sh b/gitprompt.sh
index 913d0a9..750ee83 100755
--- a/gitprompt.sh
+++ b/gitprompt.sh
@@ -482,7 +482,7 @@ function updatePrompt() {
       if [[ "x$2" == "x-n" ]] ; then
         v="$2 \"\$GIT_$1\""
       else
-        v="\"\$GIT_$1 $2\""
+        v="\"\$GIT_$1\" $2"
       fi
       if eval "test $v" ; then
         if [[ $# -lt 2 || "$3" != '-' ]]; then
```

That works perfectly and makes sense!  Thanks @ogr3 !

**Comment by kolydart** [comment]
This works for me also (see issue [#256](https://github.com/magicmonty/bash-git-prompt/issues/256#issuecomment-223612934))

**Pull request merged**
