### PR TITLE
Custom theme using prompt_callback

### PR DESCRIPTION
**Pull request by ogr3**
This is a custom theme using prompt_callback.

It generates a Debian style prompt with a truncated PWD depending on window width. Also changes the window title to user@host <truncatedPWD>

Fixes issue #155

### CODE REVIEW

**Comment by magicmonty** [comment]
Cool, thanks

**Comment by quamenzullo** [comment]
I also modified the custom theme and I had to use prompt_callback_default because using prompt_callback didn't work. Now when when these commits will be merged to the main project, it means that using prompt_callback will work? (So I have to switch back to prompt_callback in my custom theme?)

**Comment by ogr3** [comment]
Yes, prompt_callback would be the preferred way now. I'm using it myself in my theme.

**Comment by hashhar** [comment]
@ogr3 I was trying to modify your theme to only show the path relative to the git root if in a git repo, normal otherwise.

Consider
```
/home
|-- github
|    |-- repo1
|    |-- repo2
|-- no-git
|    |-- a
|    |-- b
```
I am looking for:
```
#Prompt in github/repo1/r1/r2
:git:/repo1/r1/r2      (relative to the root of the repo)

#Prompt in no-git/a/a1/a2
~/no-git/a/a1/a2       (absolute)
```

How could I do that? I tried using `rev-parse  --show-toplevel` and `--show-prefix` but couldn't get it to work as a callback.

**Comment by quamenzullo** [comment]
In .git-prompt-colors.sh, I use this (was given by a friend of mine):

```
GIT_PROMPT_START_USER="${Yellow}"
  function prompt_callback {
    local repo=$(git rev-parse --show-toplevel 2> /dev/null)
    local base=$(basename $repo)
    local pwd=$(pwd)
    local path=${pwd##$repo}
    echo -n "${Yellow}${base}${path}${ResetColor} "
  }
```
I guess you can add colons and anything in the final echo.

**Comment by hashhar** [comment]
Thanks @quamenzullo Seems like I had the wrong idea about how it worked.

**Comment by ogr3** [comment]
If you want the same functionality as the original PR @hashhar , and minimize external calls (`basename`, `pwd`), you could do this in a custom theme:

```sh
override_git_prompt_colors() {
  GIT_PROMPT_THEME_NAME="Custom"

  # Helper function that truncates $1 depending on window width
  function gp_truncate_string {
    local string=$1
    local tilde="~"
    local newPWD="${string/#${HOME}/${tilde}}"
    local pwdmaxlen=$((${COLUMNS:-80}/4))
    [ ${#newPWD} -gt $pwdmaxlen ] && newPWD="...${newPWD:3-$pwdmaxlen}"
    echo -n "$newPWD"
  }

  #Overrides the prompt_callback function used by bash-git-prompt
  function prompt_callback {
    local repo=$(git rev-parse --show-toplevel 2> /dev/null)
    local base=${repo##*/}
    local path=${PWD##$repo}
    local truncPath=$(gp_truncate_string $path)
    local finalPrompt="\u@\h: ${base}${truncPath}"

    gp_set_window_title $finalPrompt

    echo -n "${Yellow}[${finalPrompt}]${ResetColor}"
  }

  local gp_end=" _LAST_COMMAND_INDICATOR_\n${White}${Time12a}${ResetColor}"

  GIT_PROMPT_START_USER=""
  GIT_PROMPT_END_USER="${gp_end} $ "
  GIT_PROMPT_END_ROOT="${gp_end} # "
}

reload_git_prompt_colors "Custom"
```

This sets the window title and add username@machine to the prompt. I didn't add a custom prefix for the git-repo though.

**Comment by hashhar** [comment]
Thanks @ogr3

**Pull request merged**
